[template]

[template.environment]
  REACT_APP_CHAIN_ID = ""
  REACT_APP_BLOCK_SYNC_URL = ""
  REACT_APP_BLOCK_SYNC_GRAPHQL = ""
  REACT_APP_BLOCK_SCAN_URL = ""
  REACT_APP_GAIA_URL = ""
  REACT_APP_RPC_URL = ""
  REACT_APP_PDS_URL = ""
  REACT_APP_CONFIG_EXCHANGE_URL = ""
  REACT_APP_CONFIG_RELAYER_URL = ""
  REACT_APP_CONFIG_SCHEMA_URL = ""
  REACT_APP_CONFIG_ASSETLIST_URL = ""
  REACT_APP_IXO_WORLD_ORIGIN = ""
  REACT_APP_KYC_LINK = ""
  REACT_APP_ASSISTANT_URL = "-"
  REACT_APP_ENTITY_VERSION = ""
  REACT_APP_ENTITY_PAGE_VERSION = ""
  REACT_APP_EMBEDLY_KEY = "-"
  REACT_APP_GOOGLE_API_KEY = "-"
  REACT_APP_RELAYER_NODE = ""
#ixo-networks/networkconfig

[build.environment]

[build]
command = "yarn build"
functions = "functions"




