[build]
  NODE_VERSION = "18.18.2"
  base = "/"
  command = "yarn build" # Replace with your actual build command
  publish = "build" # Replace with the directory where your build's output is stored
  package = "apps/web"

[context.production]
  # Production settings (when merged to main branch)
  # You can set environment variables or different build commands specific to production

[context.deploy-preview]
  # Settings for deploy previews (for pull requests)
  # You can set environment variables or different build commands specific to PR previews
  publish = "build" # Replace with the directory where your build's output is stored.

  command = "yarn build" # Replace with your actual build command

[functions]
  directory = "functions"