name: Build and Deploy to Netlify
on:
  pull_request:
    branches:
      - dev 
    types: [opened, synchronize]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: dev
    env: 
      NODE_OPTIONS: "--max_old_space_size=8192"
      REACT_APP_BLOCK_SYNC_GRAPHQL: ${{ vars.REACT_APP_BLOCK_SYNC_GRAPHQL }}
      REACT_APP_CHAIN_ID: ${{ vars.REACT_APP_CHAIN_ID }}
      REACT_APP_BLOCK_SYNC_URL: ${{ vars.REACT_APP_BLOCK_SYNC_URL }}
      REACT_APP_BLOCK_SCAN_URL: ${{ vars.REACT_APP_BLOCK_SCAN_URL }}
      REACT_APP_GAIA_URL: ${{ vars.REACT_APP_GAIA_URL }}
      REACT_APP_RPC_URL: ${{ vars.REACT_APP_RPC_URL }}
      REACT_APP_PDS_URL: ${{ vars.REACT_APP_PDS_URL }}
      REACT_APP_CONFIG_APP: ${{ vars.REACT_APP_CONFIG_APP }}
      REACT_APP_CLIENT_URL: ${{ vars.REACT_APP_CLIENT_URL }}
      REACT_APP_IXO_WORLD_ORIGIN: ${{ vars.REACT_APP_IXO_WORLD_ORIGIN }}
      REACT_APP_KYC_LINK: ${{ vars.REACT_APP_KYC_LINK }}
      REACT_APP_ASSISTANT_URL: ${{ vars.REACT_APP_ASSISTANT_URL }}
      REACT_APP_ENTITY_VERSION: ${{ vars.REACT_APP_ENTITY_VERSION }}
      REACT_APP_ENTITY_PAGE_VERSION: ${{ vars.REACT_APP_ENTITY_PAGE_VERSION }}
      REACT_APP_EMBEDLY_KEY: ${{ vars.REACT_APP_EMBEDLY_KEY }}
      REACT_APP_GOOGLE_API_KEY: ${{ vars.REACT_APP_GOOGLE_API_KEY }}
      REACT_APP_FEE_PER_CLAIM_FEE: ${{ vars.REACT_APP_FEE_PER_CLAIM_FEE }}
      REACT_APP_FEE_PER_EVALUATION: ${{ vars.REACT_APP_FEE_PER_EVALUATION }}
      REACT_APP_FEE_OVERHEAD: ${{ vars.REACT_APP_FEE_OVERHEAD }}
      REACT_APP_RELAYER_NODE: ${{ vars.REACT_APP_RELAYER_NODE }}
      REACT_APP_MULTI_CALL_CONTRACT_ADDRESS: ${{ vars.REACT_APP_MULTI_CALL_CONTRACT_ADDRESS }}
      REACT_APP_CONFIG_ASSETLIST_URL: ${{ vars.REACT_APP_CONFIG_ASSETLIST_URL }}
      REACT_APP_CONFIG_EXCHANGE_URL: ${{ vars.REACT_APP_CONFIG_EXCHANGE_URL }}
      REACT_APP_CONFIG_RELAYER_URL: ${{ vars.REACT_APP_CONFIG_RELAYER_URL }}  
      REACT_APP_CONFIG_SCHEMA_URL: ${{ vars.REACT_APP_CONFIG_SCHEMA_URL }}
      REACT_APP_CUSTOM_THEME_URL: ${{ vars.REACT_APP_CUSTOM_THEME_URL }}
      NODE_ENV: ${{ vars.NODE_ENV }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.18.2'  # Node Version

    - name: Install Dependencies
      run: yarn

    - name: Build
      run: |
        export NODE_OPTIONS="--max_old_space_size=8192"
        yarn build  # Build Script

    - name: Deploy to dev.ixo.earth deploy preview
      uses: netlify/actions/cli@master
      id: dev_ixo_earth_deploy_preview
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: 98449c34-e6ca-47c1-9814-1a4007adb702  # Replace with your Netlify Site ID
      with:
        args: deploy --dir=apps/web/build --filter @ixo-webclient/web   # Update --dir with the directory of your build output

    - name: Deploy to yoma.ixo.earth deploy preview
      uses: netlify/actions/cli@master
      id: yoma_ixo_earth_deploy_preview
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ffd81e41-b107-4846-a472-4a69bf1991d3  # Replace with your Netlify Site ID
        REACT_APP_CONFIG_ASSETLIST_URL: https://raw.githubusercontent.com/ixofoundation/ixo-webclient/dev/apps/web/configs/yoma/asset-list.json
        REACT_APP_CONFIG_EXCHANGE_URL: https://raw.githubusercontent.com/ixofoundation/ixo-webclient/dev/apps/web/configs/yoma/exchange.json
        REACT_APP_CONFIG_RELAYER_URL: https://raw.githubusercontent.com/ixofoundation/ixo-webclient/dev/apps/web/configs/yoma/app-config.json 
        REACT_APP_CONFIG_SCHEMA_URL: https://raw.githubusercontent.com/ixofoundation/ixo-webclient/dev/apps/web/configs/yoma/config.json
        REACT_APP_CUSTOM_THEME_URL: https://raw.githubusercontent.com/ixofoundation/ixo-webclient/dev/apps/web/configs/yoma/theme.json
      with:
        args: deploy --dir=apps/web/build --filter @ixo-webclient/web   # Update --dir with the directory of your build output

    - name: Deploy to idcc.ixo.earth deploy preview
      uses: netlify/actions/cli@master
      id: idcc_ixo_earth_deploy_preview
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: 8095507c-1245-49e1-9f54-167b18c2de4b  # Replace with your Netlify Site ID
        REACT_APP_CONFIG_ASSETLIST_URL: https://raw.githubusercontent.com/ixofoundation/ixo-webclient/dev/apps/web/configs/idcc/asset-list.json
        REACT_APP_CONFIG_EXCHANGE_URL: https://raw.githubusercontent.com/ixofoundation/ixo-webclient/dev/apps/web/configs/idcc/exchange.json
        REACT_APP_CONFIG_RELAYER_URL: https://raw.githubusercontent.com/ixofoundation/ixo-webclient/dev/apps/web/configs/idcc/app-config.json 
        REACT_APP_CONFIG_SCHEMA_URL: https://raw.githubusercontent.com/ixofoundation/ixo-webclient/dev/apps/web/configs/idcc/config.json
        REACT_APP_CUSTOM_THEME_URL: https://raw.githubusercontent.com/ixofoundation/ixo-webclient/dev/apps/web/configs/idcc/theme.json
      with:
        args: deploy --dir=apps/web/build --filter @ixo-webclient/web   # Update --dir with the directory of your build output

    - name: Deploy to test.ixo.earth deploy preview
      uses: netlify/actions/cli@master
      id: test_ixo_earth_deploy_preview
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: 50ab39f7-d558-493b-8cc6-6f47fa4c8c56  # Replace with your Netlify Site ID
        REACT_APP_CONFIG_ASSETLIST_URL: https://raw.githubusercontent.com/ixofoundation/ixo-webclient/dev/apps/web/configs/testzone/asset-list.json
        REACT_APP_CONFIG_EXCHANGE_URL: https://raw.githubusercontent.com/ixofoundation/ixo-webclient/dev/apps/web/configs/testzone/exchange.json
        REACT_APP_CONFIG_RELAYER_URL: https://raw.githubusercontent.com/ixofoundation/ixo-webclient/dev/apps/web/configs/testzone/app-config.json 
        REACT_APP_CONFIG_SCHEMA_URL: https://raw.githubusercontent.com/ixofoundation/ixo-webclient/dev/apps/web/configs/testzone/config.json
        REACT_APP_CUSTOM_THEME_URL: https://raw.githubusercontent.com/ixofoundation/ixo-webclient/dev/apps/web/configs/testzone/theme.json
      with:
        args: deploy --dir=apps/web/build --filter @ixo-webclient/web   # Update --dir with the directory of your build output.

    - name: Send URLs to Slack
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        URL1=${{ steps.dev_ixo_earth_deploy_preview.outputs.NETLIFY_URL }}
        URL2=${{ steps.yoma_ixo_earth_deploy_preview.outputs.NETLIFY_URL }}
        URL3=${{ steps.idcc_ixo_earth_deploy_preview.outputs.NETLIFY_URL }}
        URL4=${{ steps.test_ixo_earth_deploy_preview.outputs.NETLIFY_URL }}

        MESSAGE="Deploy preview for dev.ixo.earth: $URL1\nDeploy preview for yoma.ixo.earth: $URL2\nDeploy preview for idcc.ixo.earth: $URL3\nDeploy preview for test.ixo.earth: $URL4\n"

        curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"$MESSAGE\"}" $SLACK_WEBHOOK_URL
