name: Build and Deploy to Netlify
on:
  pull_request:
    branches:
      - dev 

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.18.2'  # Node Version

    - name: Install Dependencies
      run: yarn

    - name: Build
      run: yarn build  # Build Script

    - name: Deploy to Netlify
      uses: netlify/actions/cli@master
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: 98449c34-e6ca-47c1-9814-1a4007adb702  # Replace with your Netlify Site ID
      with:
        args: deploy --dir=apps/web/build --prod  # Update --dir with the directory of your build output
